# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cec3e3893f25063b29de26063af412da1f075707d4c3ad0711fa69375bb5b76ac3b4f01cf3a252b882bbee12b42b7d2681777138bb90e3d6101092dd576b831

test:
  secret_key_base: c8d56c74277a03c48cfeed9650eac8a3842d5b0b23f87d493f57b46d97ce3b1e15fb7b4dbd87df6d1df10f71a1827ec2178a862207916d7028187c9129ac2498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
